### ISSUE TITLE
Doesn't fire callback for overridden methods

### ISSUE THREAD

**Issue by oozzal** [PragTob/after_do#20]
```ruby
class A
  extend AfterDo
  def a
    # ...
  end

  def b
    raise NotImplementedError
  end

  after :a do
    puts 'a was called'
  end

  after :b do
    puts 'b was called'
  end
end

class B < A
  def b
  end
end

bb = B.new
bb.a # fires callback
bb.b # doesn't fire callback
```

@PragTob, any ideas how to accomplish this?

**Comment by PragTob** [comment]
Hi @oozzal !

Thanks for the report. This is by design, e.g. you attach a callback to method `a` of class `A` and it never gets called so it is working as intended - method `a` on `B` is a different method. If you were to call `super` in the `a` implementation of `B` it'd call the callback (after the super call).

to achieve what you want it to do you'd either have to manually readd the callback  at the moment (duplication - not good) in the sub class. Theoretically after_do could be extended with an `inherit_callbacks` method that would inherit all the callbacks from super classes for methods that are overridden.

That has its dangers though. e.g.

```ruby
class A
  def a; end
  after :a, ...
end

class B < A
  def a
    super
    ...
  end

  inherit_callbacks!
end

B.new.a # calls the callback twice, once B#a and once for super (A#a)
```

Which is also confusing and to resolve it I'd have to detect super calls which I guess I don't want to do :)

Overall, not sure if this fits into this small readable library. I'd have to sketch it out and maybe drop it, or put it in plugin/other library. I'll see what it looks like if I have some time :)

Hope that answered your question, in short it's not trivial but it can be done and I definitely don't want it to be the default behavior atm :)

Tobi

**Comment by PragTob** [comment]
as no reply I'll assume this somewhat resolves it :)
